### PR TITLE
AMD/ROCm support

### PR DESCRIPTION
**Pull request by Beinsezii**
Barebones, based on the Mac config.

Verified with
```sh
pip install -U poetry
poetry install --no-root -C install/rocm
bash train_sdxl.sh
```

As it's based on the `apple` config, some libs aren't included ATM that possibly work on ROCm. Let me know if there's other important libs I can trial.

Added DeepSpeed 0.14 as it compiles fine on my GPU w/ ROCm 6

CC @bghira

### CODE REVIEW

**Comment by Beinsezii** [comment]
Also torch is pinned up to 2.3 because lower versions will fail the dependency resolve on ROCm 6, and ROCm versions < 6.0 have page fault issues on my GPU.

**Comment by bghira** [comment]
maybe a fused backwards pass would help rocm and mps use less memory

**Review by bghira — APPROVED** [review]
sounds good to me

**Comment by Beinsezii** [comment]
What is `triton-library` used for? That's the only library I couldn't get working on ROCm besides `xformers`.

I greped the whole repo and didn't see it imported anywhere.

**Comment by bghira** [comment]
it's used by torch itself to compile kernels

**Comment by Beinsezii** [comment]
`triton-library`, not `triton`? `triton` is included in the pytorch ROCm repository already.

**Comment by bghira** [comment]
thank you

**Pull request merged**
