### PR TITLE
Residues of #661

### PR DESCRIPTION
**Pull request by sayakpaul**
Sorry, should have opened as a draft first.

### CODE REVIEW

**Review by bghira — APPROVED** [review]

**Comment by bghira** [comment]
there's still many issues :(

**Comment by sayakpaul** [comment]
I am sorry?

**Comment by bghira** [comment]
https://github.com/bghira/SimpleTuner/commit/63a17a1191cec1e410747033b3a990f05b5a389d
https://github.com/bghira/SimpleTuner/commit/05e29394b04f9231dca6fb22c8c12d92b95c2fc0
https://github.com/bghira/SimpleTuner/commit/c2aadea7b62cab4a29dc88d930747b3023823ba2

**Comment by sayakpaul** [comment]
Thanks for the fixes.

**Pull request merged**
