### PR TITLE
Fixes #745 - do not throw last partial batch

### LINKED ISSUE #745: Do not throw away images if your dataset is not divisible by batch size
There has to be some reasonable way to do this.

### PR DESCRIPTION
**Pull request by burgalon**

### CODE REVIEW

**Comment by bghira** [comment]
but did you test it with multiple gpus?

**Comment by burgalon** [comment]
Yap

**Comment by bghira** [comment]
can you share the details

**Comment by bghira** [comment]
for example if we have a batch size of 4, and 1 image in the set, what happens?

**Comment by burgalon** [comment]
in the case of the dataset of 19 images, it seemed to use all the 19 images, and i'm guessing it filled the batches using torch.choice properly? Is there anything specific you'd like me to check?

**Comment by bghira** [comment]
the problem will be that the batch size must be met by the aspect sampler. or it will never yield anything

**Comment by burgalon** [comment]
in my case i was using with:
```
    "crop": true,
    "crop_aspect": "square",
    "crop_style": "center",
```
but I'm not sure it matters for this case. The training seemed to go well and it seemed like all images were used as much as I can tell....

**Pull request merged**
